### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by k4rtik** [simonpj/www.peytonjones.org#15]
Notes on presenting theses, edited by Aaron Sloman is available at https://www.cs.bham.ac.uk/research/projects/poplog/teach/theses.pdf

Other broken links common on multiple HOWTO pages:
- http://www.eecs.harvard.edu/~nr/pubs/two-abstract.html
- http://www.cs.bham.ac.uk/internal/research_students/theses.php
- https://www.microsoft.com/en-us/research/academic-program/how-to-write-a-great-research-proposal/other-resources/href=

More on https://simon.peytonjones.org/great-grant-proposal/:
- https://simon.peytonjones.org/assets/pdfs/great-research-proposal
- http://www.pkwteile.de/wissen/psani-dobry-grant-navrh
- http://www.handyorten.org/wissen/scrierea-unei-propuneri-de-finantare-bun

---

Derek Dreyer's talk slides are at https://people.mpi-sws.org/~dreyer/talks/talk-plmw21icfp.pdf (current link http://portal.acm.org/citation.cfm?id=1508244.1508275 is incorrect)

**Comment by k4rtik** [comment]
On https://simon.peytonjones.org/great-research-talk/

`Nick Nethercote also has a [useful 2-page guide[(http://www.valgrind.org/njn/good-talk.html)] about giving a talk`

should be 

> Nick Nethercote also has a [useful 2-page guide](https://web.archive.org/web/20210413034927/http://njn.valgrind.org/good-talk.html) about giving a talk

An alternate link since the original is dead is http://www.cs.um.edu.mt/gordon.pace/Teaching/HowToPresentAPaper/SupplementaryReading/nethercote.pdf

**Comment by simonpj** [comment]
Thanks Kartik

I think I have fixed all these links now; and instead of duplicating them
I've put them in a single new "research skills" page.

Would you like to check?  Thanks!

Simon

**Comment by k4rtik** [comment]
Hi Simon

That sounds like a good idea.

Here are a couple more links on that page that I found to be broken:

1. David Patterson’s talk ... [Slides](https://simon.peytonjones.org/research-skills/https%3A%2F%2Fpeople.eecs.berkeley.edu%2F~pattrsn%2Ftalks%2FBadCareer.pdf) should be https://people.eecs.berkeley.edu/~pattrsn/talks/BadCareer.pdf
2. Derek Dreyer’s PLMW’16 talk [slides](https://simon.peytonjones.org/research-skills/https%3A%2F%2Fpeople.mpi-sws.org%2F~dreyer%2Ftalks%2Ftalk-plmw16.pdf) should be https://people.mpi-sws.org/~dreyer/talks/talk-plmw21icfp.pdf (from ICFP '21's PLMW)

**Comment by simonpj** [comment]
Thanks!  I fixed both of those.  Much appreciated

Simon

**Comment by k4rtik** [comment]
You're welcome, and thanks to you for maintaining all these resources. I especially learned a lot from your HOWTOs on research talk and paper. Hope to use the grant proposal one someday.

BTW, the bottom sections of both https://simon.peytonjones.org/great-research-talk/#related-links and https://simon.peytonjones.org/great-grant-proposal/#other-resources need to be updated. They link to themselves but not to https://simon.peytonjones.org/great-research-paper/

In addition, both say "Great Great Grant".

**Comment by simonpj** [comment]
Excellent -- done!

Thanks again

Simon

**Comment by k4rtik** [comment]
Thanks @simonpj 

There is still the issue of [**Great Great** Grant Proposal](https://simon.peytonjones.org/great-research-talk/#related-links) and [**Great Great** Research paper](https://simon.peytonjones.org/great-grant-proposal/#other-resources), but I am closing the issue now as the links are fixed.

**Comment by simonpj** [comment]
> There is still the issue of [Great Great Grant Proposal](https://simon.peytonjones.org/great-research-talk/#related-links) and [Great Great Research paper](https://simon.peytonjones.org/great-grant-proposal/#other-resources),

Ah -- I missed that. Fixed now.  Thanks!
